# Basic
title: Maskter
subtitle: A blog for Sichao Wang
welcome_message: <a href="https://github.com/Masktercn" target="_blank">Visit me</a>
description: write my coding problem & life idea.
creator: <a href="http://maskter.cn">@Maskter</a>

url: "http://blog.maskter.cn"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: slate

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: Category, description: Blog's Category, url: '/categoryList/index.html/#blog'}
    - {title: Projects, description: My Projects on Github, url: 'https://github.com/Masktercn'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
plugins: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: maskter
    # duoshuo:

# Social
social:
    #weibo: onevcat
    #github: onevcat
    #twitter: onevcat
    #gplus: 107108267983477358170
    #mail: onev@onevcat.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
